server:
  port: 8080
  origin: ${ORIGIN:*}
  servlet:
    context-path: /commands
spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: commands
  rabbitmq:
    addresses: ${RABBITMQ_URI:amqp://guest:guest@localhost:5672}  
  data:
    mongodb:
        uri: ${MONGO_URI:mongodb://localhost:27017/demo}
  jackson:
    serialization:
      write-dates-as-timestamps: false
microservice:
  exchange: ${EXCHANGE:core-demo}
  queue: ${QUEUE:demo.commandhandles}
  storeName: ${STORE_NAME:account}
  routingKey: ${ROUTING_KEY:org.example.#}

